---
- hosts: all
  tasks:
    - name: Install and configure httpd web server
      block:
        - yum:
            name: httpd
            state: latest
        - service:
            name: httpd
            state: started

            #just a play under a block 
